data:
  path: 'data/input.txt'
  train_split: 0.9
  block_size: 128
  truncate: 0.05

optimizer:
  optimizer: adamw
  learning_rate: 3e-4

model:
  model: gpt
  n_embd: 384
  n_head: 6
  n_layer: 6
  dropout: 0.2


train:
  data_loader_workers: 4
  save_every: 3
  max_epochs: 10
  batch_size: 216
  max_iters: 5000
  eval_steps: 1
  device: 'cpu'
  grad_norm_clip: 1.0
  snapshot_path: gpt_snapshot.pt
  use_amp: False
