apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: gpt
spec:
  serviceName: "gpt"
  replicas: 2
  selector:
    matchLabels:
      app: gpt
  template:
    metadata:
      labels:
        app: gpt
    spec:
      containers:
      - name: gpt
        image: <replace-me>
        ports:
        - containerPort: 5000
          name: server
        volumeMounts:
        - name: datadir
          mountPath: /var/lib/gpt
  volumeClaimTemplates:
  - metadata:
      name: datadir
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi